// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "github/OfrenDialsa/go-gin-starter/internal/model"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, audit
func (_m *AuditLogRepository) Create(ctx context.Context, tx pgx.Tx, audit *model.AuditLog) error {
	ret := _m.Called(ctx, tx, audit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *model.AuditLog) error); ok {
		r0 = rf(ctx, tx, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
