// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "github/OfrenDialsa/go-gin-starter/internal/model"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// LogJobRepository is an autogenerated mock type for the LogJobRepository type
type LogJobRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, job
func (_m *LogJobRepository) Create(ctx context.Context, tx pgx.Tx, job *model.LogJob) error {
	ret := _m.Called(ctx, tx, job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *model.LogJob) error); ok {
		r0 = rf(ctx, tx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByJobId provides a mock function with given fields: ctx, tx, jobId
func (_m *LogJobRepository) FindByJobId(ctx context.Context, tx pgx.Tx, jobId string) (*model.LogJob, error) {
	ret := _m.Called(ctx, tx, jobId)

	if len(ret) == 0 {
		panic("no return value specified for FindByJobId")
	}

	var r0 *model.LogJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (*model.LogJob, error)); ok {
		return rf(ctx, tx, jobId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) *model.LogJob); ok {
		r0 = rf(ctx, tx, jobId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LogJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, jobId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFailedForRetry provides a mock function with given fields: ctx, limit
func (_m *LogJobRepository) GetFailedForRetry(ctx context.Context, limit int) ([]model.LogJob, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetFailedForRetry")
	}

	var r0 []model.LogJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.LogJob, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.LogJob); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LogJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementRetry provides a mock function with given fields: ctx, tx, jobId
func (_m *LogJobRepository) IncrementRetry(ctx context.Context, tx pgx.Tx, jobId string) error {
	ret := _m.Called(ctx, tx, jobId)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, jobId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsCompleted provides a mock function with given fields: ctx, tx, jobId
func (_m *LogJobRepository) MarkAsCompleted(ctx context.Context, tx pgx.Tx, jobId string) error {
	ret := _m.Called(ctx, tx, jobId)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, jobId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsFailed provides a mock function with given fields: ctx, tx, jobId, errMsg
func (_m *LogJobRepository) MarkAsFailed(ctx context.Context, tx pgx.Tx, jobId string, errMsg string) error {
	ret := _m.Called(ctx, tx, jobId, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, string) error); ok {
		r0 = rf(ctx, tx, jobId, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLogJobRepository creates a new instance of LogJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogJobRepository {
	mock := &LogJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
