// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github/OfrenDialsa/go-gin-starter/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MailerService is an autogenerated mock type for the MailerService type
type MailerService struct {
	mock.Mock
}

// Send provides a mock function with given fields: req
func (_m *MailerService) Send(req dto.MailerRequest) (string, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.MailerRequest) (string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.MailerRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(dto.MailerRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMailerService creates a new instance of MailerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailerService {
	mock := &MailerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
