// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NsqClient is an autogenerated mock type for the NsqClient type
type NsqClient struct {
	mock.Mock
}

// Publish provides a mock function with given fields: topic, body
func (_m *NsqClient) Publish(topic string, body []byte) error {
	ret := _m.Called(topic, body)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(topic, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with no fields
func (_m *NsqClient) Stop() {
	_m.Called()
}

// NewNsqClient creates a new instance of NsqClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNsqClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NsqClient {
	mock := &NsqClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
