// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github/OfrenDialsa/go-gin-starter/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ProducerService is an autogenerated mock type for the ProducerService type
type ProducerService struct {
	mock.Mock
}

// PublishEvent provides a mock function with given fields: event
func (_m *ProducerService) PublishEvent(event dto.DomainEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.DomainEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProducerService creates a new instance of ProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerService {
	mock := &ProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
