// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github/OfrenDialsa/go-gin-starter/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockMailer is an autogenerated mock type for the Sender type
type MockMailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *MockMailer) Send(_a0 dto.MailgunRequest) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.MailgunRequest) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(dto.MailgunRequest) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(dto.MailgunRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
