// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "github/OfrenDialsa/go-gin-starter/internal/model"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, session
func (_m *SessionRepository) Create(ctx context.Context, session *model.UserSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSession provides a mock function with given fields: ctx, sessionId
func (_m *SessionRepository) DeleteSession(ctx context.Context, sessionId string) error {
	ret := _m.Called(ctx, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBySessionId provides a mock function with given fields: ctx, sessionId
func (_m *SessionRepository) GetBySessionId(ctx context.Context, sessionId string) (*model.UserSession, error) {
	ret := _m.Called(ctx, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for GetBySessionId")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSession, error)); ok {
		return rf(ctx, sessionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSession); ok {
		r0 = rf(ctx, sessionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByToken provides a mock function with given fields: ctx, tokenHash, tokenType
func (_m *SessionRepository) GetByToken(ctx context.Context, tokenHash string, tokenType string) (*model.UserSession, error) {
	ret := _m.Called(ctx, tokenHash, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.UserSession, error)); ok {
		return rf(ctx, tokenHash, tokenType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.UserSession); ok {
		r0 = rf(ctx, tokenHash, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tokenHash, tokenType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeAllExcept provides a mock function with given fields: ctx, userId, sessionId
func (_m *SessionRepository) RevokeAllExcept(ctx context.Context, userId string, sessionId string) error {
	ret := _m.Called(ctx, userId, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllExcept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userId, sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllUserSessions provides a mock function with given fields: ctx, tx, userId
func (_m *SessionRepository) RevokeAllUserSessions(ctx context.Context, tx pgx.Tx, userId string) error {
	ret := _m.Called(ctx, tx, userId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeBySessionId provides a mock function with given fields: ctx, sessionID
func (_m *SessionRepository) RevokeBySessionId(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeBySessionId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeByToken provides a mock function with given fields: ctx, tokenHash
func (_m *SessionRepository) RevokeByToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, session
func (_m *SessionRepository) Update(ctx context.Context, session *model.UserSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
